### ISSUE TITLE
Feature request: more fine-grained waits

### ISSUE THREAD

**Issue by eirslett** [Chion82/redux-wait-for-action#1]
It would be nice with a possibility to add a precondition for resolving actions. A problem can arise in race conditions, where multiple calls are dispatched in parallel. Then, the wrong promise might be resolved!

```javascript
function fetchArticleAndLog (id) {
  dispatch({
    type: 'FETCH_ARTICLE',
    id,
    [WAIT_FOR_ACTION]: 'FETCH_ARTICLE_SUCCESS'
  }).then(res => console.log('got article with id', res.id);
}

fetchArticleAndLog(1); // logs 1
fetchArticleAndLog(2); // logs 2
fetchArticleAndLog(3); // logs 4 <-- error because of race condition, article 3 took a long time to load
fetchArticleAndLog(4); // logs 3 <-- error because of race condition, article 4 was quick to load
```

A way to solve this, could be to introduce conditionals:

```javascript
function fetchArticleAndLog (id) {
  dispatch({
    type: 'FETCH_ARTICLE',
    id,
    [WAIT_FOR]: action => action.type === 'FETCH_ARTICLE_SUCCESS' && action.id === id
  }).then(res => console.log('got article with id', res.id);
}
```

**Comment by Chion82** [comment]
Agree. Passing a function containing conditions  instead of a string of action type solves this problem. This feature will be added ASAP. 

Thanks for your advice! :)

**Comment by Chion82** [comment]
Hi, this feature is now added. Please upgrade this package to `0.0.6` and checkout [README: Basic Usage](https://github.com/Chion82/redux-wait-for-action#basic-usage). 

Hope it helps you :)

**Comment by eirslett** [comment]
Thanks a lot! That was quick! :) 👍
