### ISSUE TITLE
how can i get the logic inside static fetch data

### ISSUE THREAD

**Issue by SaiRO97** [Chion82/redux-wait-for-action#11]
Hello, I have a problem with redux-wait-for-action, I need to add the noindex meta tag to the head, if the array of elements from the backend is empty. When I use inspect, it works, but when I open the source code view page, the meta tag is not added . Can I use redux-wait-for-action to solve a problem?

I tried this 
`static fetchData({dispatch}){
    dispatch({
      type: HELMET_NOINDEX,
      isShow: true
    })
  }`

action
`export const helmetNoindex = isShow => ({type: HELMET_NOINDEX, isShow})`

this works when the isShow property takes a static value like true, but when I tried to use a dynamic variable like this

`static fetchData({dispatch, isAddMeta}){
    dispatch({
      type: HELMET_NOINDEX,
      isShow: isAddMeta
    })
  }`

and call in componentDidMount 
`ListingsAndMapContainer.fetchData({dispatch: this.props.dispatch, isAddMeta: false})`
isAddMeta is undefined on server. I used react-redux and express on server, please tell me how can I solve this problem or use own props inside static fetchData ?

**Comment by frodare** [comment]
If I understand correctly, you will need to add that meta tag on the server side.  If you see it correctly in the inspector, your front-end code is probably working correctly.

**Comment by SaiRO97** [comment]
Yeah but I need to transfer properties to the server, can I do it with redux-wait-for-action? Cause when items from backend empty, store on the server not changing

**Comment by Chion82** [comment]
@SaiRO97  
You can put the data in the URL arguments so that you can read it from the server.

However, If the data you want to send to the server is generated by user interaction, there's nothing to do with this module because it only works with first-screen server-side rendering.
