### ISSUE TITLE
Callback Arguments

### ISSUE THREAD

**Issue by frodare** [Chion82/redux-wait-for-action#3]
I would like to use this middleware, however, I don't want to alter the existing actions to add a payload or data field.  Would you be interested in a PR that would allow the callback argument to be changed?

New symbols could be used to hold two functions that would return data from the action, where the defaults would be:

`CALLBACK_ARGUMENT: action => action.payload || action.data || {}` 

and

`ERROR_CALLBACK_ARGUMENT: action => action.error || action.err || new Error('action.error not specified.')` 

so that the behavior wouldn't change for people already using this middleware, but allow users to change the callbacks to whatever they would need. I would be happy to submit a PR if you are interested.

Thanks!

**Comment by Chion82** [comment]
Sounds reasonable. For original design, `action => action.payload || action.data` is only for FSA-compliant actions. In case action is non-FSA, the corresponding payload can be accessed from the global state by calling `store.getState()`, which means the reducer has to save that payload in the state when the action triggers.

Adding the `CALLBACK_ARGUMENT` parameter is a better way to simplify this flow. Appreciated if you would like to fire a PR :)

Thanks.

**Comment by Chion82** [comment]
PR is merged. This feature is published with version 0.0.7. Thanks very much.
